name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Notify local server to pull latest changes and restart
      run: |
        curl -X POST "https://shown-speaks-plugin-dietary.trycloudflare.com/deploy" \
          -H "Content-Type: application/json" \
          -H "Secret: ${{ secrets.DEPLOY_SECRET }}"


