name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Notify local server to pull latest changes and restart
      run: |
        curl -X POST "https://shown-speaks-plugin-dietary.trycloudflare.com/deploy" \
          -H "Content-Type: application/json" \
          -H "Secret: ${{ secrets.DEPLOY_SECRET }}"

sudo cloudflared service install eyJhIjoiOTk4YmU3MTc3NzU4ZjU2ODIzZjg3MmRlMTk0NjU4ZjAiLCJ0IjoiYjEzNDk1NTEtMzMyYy00YTBkLWE2OWYtZDkzZjE0ZmZjMWJlIiwicyI6Ill6TmtPVGcxTUdRdFl6a3daQzAwTldSakxXSTROVFl0TmpFNVlXTTFZMlJtTkRjMSJ9
